Repository softeerbootcamp-3rd/softee5-mobil2team-FE, pull requests merged in 2024-01, with the labels that each got.

#82 Feat/#69 near wagle
  JS/controllers/api/getApi.js
  JS/controllers/api/postApi.js
  JS/controllers/events/onClick.js
  JS/controllers/handlers/modalHandler.js
  JS/controllers/handlers/nearWagleHandler.js
  JS/controllers/handlers/textCountHandler.js
  JS/controllers/handlers/uploadCardHandler.js
  JS/controllers/init/initEventListener.js
  JS/controllers/render.js
  JS/controllers/utils/getStationId.js
  JS/data.js
  JS/pages.js
  JS/views/components/ButtonViews.js
  JS/views/components/CardView.js
  JS/views/components/LoaderViews.js
  JS/views/components/TagView.js
  JS/views/components/UploadHeaderView.js
  JS/views/components/UploadPhotoListView.js
  JS/views/components/UploadPhotoView.js
  JS/views/components/UploadTagListView.js
  JS/views/components/wagle/WagleTagListView.js
  JS/views/pages/HomeView.js
  JS/views/pages/UploadView.js
  SCSS/components/btns.scss
  SCSS/components/card.scss
  SCSS/components/tag.scss
  SCSS/pages/home.scss
  SCSS/pages/upload.scss
  index.js
  public/hot.svg
  public/logo.svg
  public/near_img.svg
  public/pin/pin_1.svg
  public/pin/pin_10.svg
  public/pin/pin_11.svg
  public/pin/pin_2.svg
  public/pin/pin_3.svg
  public/pin/pin_4.svg
  public/pin/pin_5.svg
  public/pin/pin_6.svg
  public/pin/pin_7.svg
  public/pin/pin_8.svg
  public/pin/pin_9.svg
  public/tag/tag_img_1.svg
  public/tag/tag_img_10.svg
  public/tag/tag_img_11.svg
  public/tag/tag_img_2.svg
  public/tag/tag_img_3.svg
  public/tag/tag_img_4.svg
  public/tag/tag_img_5.svg
  public/tag/tag_img_6.svg
  public/tag/tag_img_7.svg
  public/tag/tag_img_8.svg
  public/tag/tag_img_9.svg
  public/tooltip_polygon.svg
Labels: enhancement

#78 feat: 노선도 헤더, 핫한역정보 추가
  JS/controllers/api/getApi.js
  JS/controllers/render.js
  JS/data.js
  JS/pages.js
  JS/views/components/HotStationListView.js
  JS/views/components/HotStationView.js
  JS/views/pages/HomeView.js
  SCSS/pages/home.scss
  public/home_header_img.svg
  public/home_header_title.svg
  public/hot_img.svg
Labels: enhancement, fix

#83 dev pull main
  JS/controllers/api/getApi.js
  JS/controllers/handlers/nearWagleHandler.js
Labels: duplicate, deployment

#80 와글페이지 태그별 분류
  JS/controllers/api/getApi.js
  JS/controllers/handlers/uploadCardHandler.js
  JS/data.js
  JS/views/components/wagle/WagleTagListView.js
Labels: enhancement

#81 feat: 좋아요 기능 추가 (API호출함수: postApi.js / 좋아요 누를때마다 뷰에서 카운트 증가 : likePostHandler.js)
  JS/controllers/api/postApi.js
  JS/controllers/events/onClick.js
  JS/controllers/handlers/likePostHandler.js
  JS/views/components/CardFooterView.js
Labels: enhancement

#89 feat: 핫한 역 선택 시 페이지 이동
  JS/views/components/HotStationView.js
Labels: enhancement

#90 Feat/#55 tag post
  JS/controllers/api/getApi.js
  JS/controllers/api/postApi.js
  JS/controllers/handlers/uploadCardHandler.js
  JS/controllers/render.js
  JS/data.js
  JS/pages.js
  JS/views/components/LoaderViews.js
  JS/views/components/TagView.js
  JS/views/components/UploadTagListView.js
  JS/views/components/wagle/WagleTagListView.js
  JS/views/pages/HomeView.js
  JS/views/pages/WagleView.js
  SCSS/pages/wagle.scss
  public/pin/pin_default.svg
  public/tag/tag_img_default.svg
Labels: enhancement, fix

#94 fix: fix margin
  SCSS/pages/wagle.scss
Labels: enhancement, fix

#92 feat: 좋아요 누를때마다 애니메이션
  JS/controllers/handlers/likePostHandler.js
  JS/views/components/CardFooterView.js
  SCSS/components/card.scss
  public/heart_img.svg
Labels: enhancement

#95 Fix#93 css
  JS/controllers/handlers/uploadCardHandler.js
  SCSS/pages/wagle.scss
Labels: fix

#98 HOTFIX: fix ssl problem
  index.html
  output/index.html
Labels: fix, deployment

#99 ROLLBACK
  index.html
  output/index.html
Labels: bug, deployment

#102 Feat#56 home tag
  JS/controllers/api/getApi.js
  JS/controllers/api/postApi.js
  JS/controllers/render.js
  JS/pages.js
  JS/views/components/ButtonViews.js
  JS/views/components/CardView.js
  JS/views/components/TagView.js
  JS/views/components/UploadTagListView.js
  JS/views/components/wagle/WagleTagListView.js
  JS/views/pages/HomeView.js
  SCSS/pages/home.scss
Labels: enhancement

#108 와글 페이지 태그 인덱스 조정
  JS/controllers/render.js
Labels: bug, fix

#109 Deploy
  output/JS/controllers/api/getApi.js
  output/JS/controllers/handlers/uploadCardHandler.js
  output/JS/controllers/render.js
  output/JS/pages.js
  output/vercel.json
  vercel.json
Labels: fix, deployment

#105 4차 배포
  JS/controllers/api/getApi.js
  JS/controllers/handlers/likePostHandler.js
  JS/controllers/handlers/uploadCardHandler.js
  JS/controllers/render.js
  JS/pages.js
  JS/views/components/ButtonViews.js
  JS/views/components/CardFooterView.js
  JS/views/components/wagle/WagleEmptyView.js
  assets/card_img.svg
  assets/heart_img.svg
  assets/tag_img.svg
  assets/triangle_img.svg
  output/JS/controllers/api/getApi.js
  output/JS/controllers/handlers/likePostHandler.js
  output/JS/controllers/handlers/uploadCardHandler.js
  output/JS/controllers/render.js
  output/JS/pages.js
  output/JS/views/components/ButtonViews.js
  output/JS/views/components/CardFooterView.js
  output/JS/views/components/wagle/WagleEmptyView.js
  output/assets/card_img.svg
  output/assets/heart_img.svg
  output/assets/tag_img.svg
  output/assets/triangle_img.svg
  output/public/empty_img.svg
  output/vercel.json
  public/empty_img.svg
  vercel.json
Labels: wontfix, deployment

#112 fix: fix tag selection
  JS/controllers/render.js
Labels: fix

#113 Deploy
  JS/controllers/render.js
  output/JS/controllers/render.js
  output/JS/views/components/HotStationView.js
  output/README.md
Labels: deployment

#115 5차 배포
  JS/controllers/render.js
  JS/views/components/HotStationView.js
  README.md
  output/JS/controllers/render.js
  output/JS/views/components/HotStationView.js
  output/README.md
Labels: deployment

#116 Deploy
  JS/controllers/handlers/uploadCardHandler.js
  document/dictionary.md
  document/ground_rule.md
  document/trouble_shooting.md
  output/JS/controllers/handlers/uploadCardHandler.js
  output/document/dictionary.md
  output/document/ground_rule.md
  output/document/trouble_shooting.md
Labels: documentation, fix, deployment

#117 6차 배포
  JS/controllers/handlers/uploadCardHandler.js
  README.md
  document/dictionary.md
  document/ground_rule.md
  document/trouble_shooting.md
  output/JS/controllers/handlers/uploadCardHandler.js
  output/document/dictionary.md
  output/document/ground_rule.md
  output/document/trouble_shooting.md
Labels: deployment

#118 HOTFIX: fix page size
  JS/controllers/api/getApi.js
  output/JS/controllers/api/getApi.js
Labels: bug, fix, deployment

#119 HOTFIX: fix card padding
  SCSS/components/card.scss
  output/SCSS/components/card.scss
Labels: bug, fix, deployment

#121 HOTFIX: make pin center
  SCSS/pages/home.scss
  output/SCSS/pages/home.scss
Labels: bug, fix, deployment

#122 HOTFIX: fix animation
  SCSS/pages/home.scss
  output/SCSS/pages/home.scss
Labels: bug, fix, deployment

#123 HOTFIX: fix animation scale
  SCSS/pages/home.scss
  output/SCSS/pages/home.scss
Labels: bug, fix, deployment

#124 HOTFIX
  .gitignore
  JS/controllers/api/getApi.js
  JS/controllers/api/postApi.js
Labels: deployment

#127 Main
  .gitignore
  JS/controllers/api/getApi.js
  JS/controllers/api/postApi.js
  SCSS/components/card.scss
  SCSS/pages/home.scss
  output/JS/controllers/api/getApi.js
  output/JS/controllers/api/postApi.js
  output/SCSS/components/card.scss
  output/SCSS/pages/home.scss
Labels: deployment

#130 7차 배포
  JS/controllers/handlers/screenSizeHandler.js
  JS/controllers/init/initUploadModal.js
  JS/pages.js
  JS/views/components/HotStationListView.js
  JS/views/components/LoaderViews.js
  JS/views/components/card/BothCardView.js
  JS/views/components/card/CardFooterView.js
  JS/views/components/card/CardHeaderView.js
  JS/views/components/card/CardView.js
  JS/views/components/card/OnlyImgCardView.js
  JS/views/components/card/OnlyTextCardView.js
  JS/views/components/upload/UploadHeaderView.js
  JS/views/components/upload/UploadPhotoListView.js
  JS/views/components/upload/UploadPhotoView.js
  JS/views/components/upload/UploadTagListView.js
  JS/views/components/wagle/WagleMainView.js
  JS/views/pages/UploadView.js
  README.md
  SCSS/pages/home.scss
  document/trouble_shooting.md
  index.js
  output/JS/controllers/handlers/screenSizeHandler.js
  output/JS/controllers/init/initUploadModal.js
  output/JS/pages.js
  output/JS/views/components/HotStationListView.js
  output/JS/views/components/LoaderViews.js
  output/JS/views/components/card/BothCardView.js
  output/JS/views/components/card/CardFooterView.js
  output/JS/views/components/card/CardHeaderView.js
  output/JS/views/components/card/CardView.js
  output/JS/views/components/card/OnlyImgCardView.js
  output/JS/views/components/card/OnlyTextCardView.js
  output/JS/views/components/upload/UploadHeaderView.js
  output/JS/views/components/upload/UploadPhotoListView.js
  output/JS/views/components/upload/UploadPhotoView.js
  output/JS/views/components/upload/UploadTagListView.js
  output/JS/views/components/wagle/WagleMainView.js
  output/JS/views/pages/UploadView.js
  output/README.md
  output/SCSS/pages/home.scss
  output/document/trouble_shooting.md
  output/index.js
Labels: refactoring

#132 feat: add pwa manifest
  index.html
  manifest.json
  output/index.html
  output/manifest.json
  output/public/icon/icon_192.png
  output/public/icon/icon_512.png
  public/icon/icon_192.png
  public/icon/icon_512.png
Labels: enhancement

#133 PWA 적용
  index.html
  manifest.json
  output/index.html
  output/manifest.json
  output/public/icon/icon_192.png
  output/public/icon/icon_512.png
  public/icon/icon_192.png
  public/icon/icon_512.png
Labels: enhancement, deployment

#134 Feat#131 pwa
  manifest.json
  output/manifest.json
Labels: enhancement

#135 PWA manifest 수정
  manifest.json
  output/manifest.json
Labels: enhancement, fix, deployment

#136 fix: fix manifest
  manifest.json
  output/manifest.json
Labels: fix, deployment

#137 PWA manifest 수정
  manifest.json
  output/manifest.json
Labels: deployment

#139 Feat#131 pwa
  index.html
  output/index.html
Labels: deployment

#140 meta tag 설정
  README.md
  index.html
  output/index.html
Labels: deployment

#141 Feat#138 seo
  JS/views/components/ButtonViews.js
  JS/views/components/wagle/WagleEmptyView.js
  JS/views/pages/HomeView.js
  output/JS/views/components/ButtonViews.js
  output/JS/views/components/wagle/WagleEmptyView.js
  output/JS/views/pages/HomeView.js
  output/README.md
  output/index.html
  output/public/robot.txt
  public/robot.txt
Labels: enhancement

#142 SEO 설정
  JS/views/components/ButtonViews.js
  JS/views/components/wagle/WagleEmptyView.js
  JS/views/pages/HomeView.js
  output/JS/views/components/ButtonViews.js
  output/JS/views/components/wagle/WagleEmptyView.js
  output/JS/views/pages/HomeView.js
  output/README.md
  output/index.html
  output/public/robot.txt
  public/robot.txt
Labels: deployment

#143 fix: change robots.txt name
  output/public/robots.txt
  public/robots.txt
Labels: bug, fix

#144 robots.txt 이름 수정
  output/public/robots.txt
  public/robots.txt
Labels: fix

#145 Feat#138 seo
  JS/controllers/utils/escapeTextForBrowser.js
  JS/controllers/utils/getDate.js
  JS/views/components/card/BothCardView.js
  JS/views/components/card/CardView.js
  JS/views/components/card/OnlyTextCardView.js
Labels: bug, enhancement, fix

#146 XSS 방지
  JS/controllers/utils/escapeTextForBrowser.js
  JS/controllers/utils/getDate.js
  JS/views/components/card/BothCardView.js
  JS/views/components/card/CardView.js
  JS/views/components/card/OnlyTextCardView.js
Labels: bug, enhancement, fix, deployment

#148 feat: add build file for preventing xss
  output/JS/controllers/utils/escapeTextForBrowser.js
  output/JS/controllers/utils/getDate.js
  output/JS/views/components/card/BothCardView.js
  output/JS/views/components/card/CardView.js
  output/JS/views/components/card/OnlyTextCardView.js
Labels: enhancement, fix

#149 xss 방지
  output/JS/controllers/utils/escapeTextForBrowser.js
  output/JS/controllers/utils/getDate.js
  output/JS/views/components/card/BothCardView.js
  output/JS/views/components/card/CardView.js
  output/JS/views/components/card/OnlyTextCardView.js
Labels: deployment
